in_file='../data/swiss_poster_links.csv'
out_file='../data/swiss_poster_data.pt'
anno_file='../data/poster_anno.xlsx'

english_topics=[
    'nuclear accidents',
    'nuclear waste',
    'protest',
    'environmentalism'
    ]

form_en='An article'
english_prompts=[f'{form_en} concerning {query.lower()}' for query in english_topics]

german_topics=[
    'Störfall',
    'Atomabfall',
    'Protest',
    'Umweltschutz'
    ]
form_de='Ein Artikel'
german_prompts=[f"{form_de} über {query}" for query in german_topics]

extra_stopwords=['Störfall','Umweltschutz','Waldsterben','Unfall','Atomabfall','Protest']

system_role_translator="You are a professional translator in German language.\
            I will give you some articles, and you need to translate them from German to English.\
            Note the German article might contain some typos or errors, you must do as a professional translator in such cases.\
            Plus, please remove unnecessary symbols such as line breaks, paragraph breaks, spaces, and tabs, etc.\
            Only output translated articles."

system_role_editor="You are a helpful assistant specialized in cleaning and normalizing metadata.\
            Your job is to standardize information, fix formatting issues, remove extraneous symbols and correct any capitalization errors.\
            I will give you some articles of different lengths and you need to clean these data.\
            In principle, the length of cleaned data should be no longer than that of metadata. If the metadata is empty, the cleaned data should also be empty.\
            Do not add verbose text generated by you. Return only the cleaned data."

system_role_de_summarizer="You are a prefessional German litterateur with good comprehesion.\
            I will show you some articles, and you need to summarize them using concise sentences in German.\
            Note the German articles might contain some typos, special symbols, or errors, so you must distinguish them yourself when reading.\
            Output only the sammarization of given articles, and it should not exceed 76 words."

system_role_en_summarizer="You are a prefessional German translator with good comprehesion.\
            I will show you some articles, and you need to summarize them using concise sentences in English.\
            Note the German articles might contain some typos, special symbols, or errors, so you must distinguish them yourself when reading.\
            Output only the English sammarization of given articles, and it should not exceed 76 words."

llama="meta-llama/Meta-Llama-3.1-8B-Instruct"
deepseek='deepseek-ai/DeepSeek-R1-Distill-Llama-8B'
model_translate="Helsinki-NLP/opus-mt-de-en"
qwen='Qwen/Qwen2.5-7B-Instruct-1M'

top_k=10

if __name__=='__main__':
    print(extra_stopwrods)
